const router = require('express').Router();
const OperationsController = require("./../../controllers/operationsController")
const authMiddleware = require('./../../middlewares/authMiddlewares');

router.route("/thisday")
    .post(authMiddleware.requireAuth, OperationsController.getThisDaySummary)
router.route("/thismonth")
    .post(authMiddleware.requireAuth, OperationsController.getThisMonthSummary)
router.route("/daily")
    .post(authMiddleware.requireAuth, OperationsController.getDailySummary)
router.route("/monthly")
    .post(authMiddleware.requireAuth, OperationsController.getMonthlySummary)
router.route("/client")
    .post(authMiddleware.requireAuth, OperationsController.getClientSummary)
router.route("/input")
    .post(authMiddleware.requireAuth, OperationsController.inputTransaction)
router.route("/inventory")
    .post(authMiddleware.requireAuth, OperationsController.inventoryUpdate)
router.route("/summary")
    .post(authMiddleware.requireAuth, OperationsController.mainPageData)
router.route("/delete")
    .post(authMiddleware.requireAuth, OperationsController.deleteTransaction)
router.route("/sales")
    .post(authMiddleware.requireAuth, OperationsController.salesSummary)
router.route("/salesdel")
    .post(authMiddleware.requireAuth, OperationsController.deleteSales)
router.route("/insertsales")
    .post(authMiddleware.requireAuth, OperationsController.insertSales)
router.route("/current_cycle")
    .post(authMiddleware.requireAuth, OperationsController.getCurrentCycle)
router.route("/cycle")
    .post(authMiddleware.requireAuth, OperationsController.getAllCycle)
router.route("/specific_cycle")
    .post(authMiddleware.requireAuth, OperationsController.getCycle)
router.route("/edit_sales")
    .post(authMiddleware.requireAuth, OperationsController.editSales)

module.exports = router;